In [1]:
import os
import xlwings
import numpy as np
import pandas as pd 

In [21]:
# 常量设置
RATIO_USUAL_SCORE = 0.2  # 平时成绩比例
RATIO_EXPERIMENT = 0.2   # 实验成绩比例
RATIO_FINAL_SCORE = 0.6  # 期末成绩比例
RATIO_SCORE_CLASS= RATIO_FINAL_SCORE

In [3]:
Qimo_table = pd.read_excel('2022春_B机制191-192流体力学基础与液压气动技术-V2-20221108.xlsx', 
                                   index_col=None, header=None, sheet_name='期末考试')
print(Qimo_table)
course_target_class = np.array((Qimo_table.iloc[3,4:-1])) 
print(course_target_class) 


     0       1             2       3        4    5    6    7    8    9    10  \
0   NaN     NaN           NaN     NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1   NaN     NaN           NaN     NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2   NaN     NaN           NaN      题型  简答题（60）  NaN  NaN  NaN  NaN  NaN  NaN   
3   NaN     NaN           NaN  课程目标类别        1    1    1    1    2    2    3   
4   NaN     NaN           NaN    每题分值        6    6    6    6    6    6    6   
..  ...     ...           ...     ...      ...  ...  ...  ...  ...  ...  ...   
81   76  B机制192  190701011068     曹远荣        6    6    6    6    6    6    6   
82   77  B机制192  190701011073     朱亚东        6    6    6    6    6    6    6   
83   78  B机制192  190701011137     冯猛超        6    6    6    6    6    6    6   
84   79  B机制192  190701011138     姚宗君        4    6    6    6    6    6    6   
85   80  B机制192  190701011149     罗治华        6    6    6    6    6    6    6   

     11   12   13       14   15       1

In [4]:
Qimo_score = np.array(Qimo_table.iloc[6:,4:-1]) 
Qimo_score[:,0]


array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       5, 6, 6, 5, 6, 6, 6, 6, 6, 4, 6, 6, 5, 6, 6, 6, 6, 6, 6, 4, 6, 4,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6], dtype=object)

In [5]:
loc_target_one = np.argwhere(course_target_class==1).reshape((-1)) # 满足条件的索引值
loc_target_two = np.argwhere(course_target_class==2).reshape((-1)) # 满足条件的索引值
loc_target_three = np.argwhere(course_target_class==3).reshape((-1)) # 满足条件的索引值

print(loc_target_one,loc_target_two,loc_target_three)  

[ 0  1  2  3 10] [ 4  5 11] [ 6  7  8  9 12]


In [6]:
Fullscore_each_examination_question = np.array((Qimo_table.iloc[4,4:-1])).reshape((-1))
print(Fullscore_each_examination_question) 

[6 6 6 6 6 6 6 6 6 6 10 10 20]


In [12]:
np.sum(Fullscore_each_examination_question,axis=0)

100

In [31]:
# 达成度目标=1 计算
### 数据索引
# 学生分数
scorelist_student_target_one=[] 

for i in range(len(loc_target_one)): 
    scorelist_student_target_one.append( Qimo_score[:,loc_target_one[i]] ) 
scorearr_target_one = np.array(scorelist_student_target_one).T 
# print('学生分数', scorearr_target_one) 

# 每题题目分数 
FullscoreEEQ_list_target_one=[] 
for i in range(len(loc_target_one)):   
    FullscoreEEQ_list_target_one.append(Fullscore_each_examination_question[loc_target_one[i]] )  

# print('每题题目分数', FullscoreEEQ_list_target_one)

### 数据计算
# 实际满分(百分制) - 比例满分 - 学生得分 - 得分比例 - 目标1得分
RealFullscore_target_one_Total = sum(FullscoreEEQ_list_target_one) / np.sum(Fullscore_each_examination_question)  *100  # 实际满分(百分制)
print('实际满分(百分制)', RealFullscore_target_one_Total)
# 比例满分 (乘以比例后的分数) 
RatioFullscore_target_one = RealFullscore_target_one_Total * RATIO_SCORE_CLASS 
# 学生得分
Score_student_target_one_Total = np.sum(scorearr_target_one, axis=1) 
# 得分比例
Ratio_score_target_one = np.around((Score_student_target_one_Total/RealFullscore_target_one_Total).astype(float) ,decimals=3)
print( Ratio_score_target_one ) 
# 目标1得分 = 比例满分 * 得分比例 
Score_target_one =np.around( ( RatioFullscore_target_one * Ratio_score_target_one).astype(float) ,decimals=3)
print(Score_target_one)

实际满分(百分制) 34.0
[1.    1.    1.    0.912 1.    0.971 1.    1.    1.    1.    0.941 1.
 0.971 1.    0.971 0.971 0.971 0.971 0.971 1.    1.    1.    0.971 1.
 1.    0.912 1.    0.971 1.    1.    1.    0.941 1.    1.    0.941 0.971
 0.971 1.    0.941 0.971 1.    0.941 1.    0.941 1.    0.912 1.    1.
 1.    1.    0.971 1.    1.    1.    0.912 0.971 0.971 1.    0.971 0.912
 1.    1.    1.    1.    1.    1.    1.    1.    0.912 1.    1.    1.
 1.    1.    1.    1.    1.    1.    0.941 1.   ]
[20.4   20.4   20.4   18.605 20.4   19.808 20.4   20.4   20.4   20.4
 19.196 20.4   19.808 20.4   19.808 19.808 19.808 19.808 19.808 20.4
 20.4   20.4   19.808 20.4   20.4   18.605 20.4   19.808 20.4   20.4
 20.4   19.196 20.4   20.4   19.196 19.808 19.808 20.4   19.196 19.808
 20.4   19.196 20.4   19.196 20.4   18.605 20.4   20.4   20.4   20.4
 19.808 20.4   20.4   20.4   18.605 19.808 19.808 20.4   19.808 18.605
 20.4   20.4   20.4   20.4   20.4   20.4   20.4   20.4   18.605 20.4
 20.4   20.4   20.4   

In [34]:
# 达成度目标=NUM 计算
### 数据索引
# 学生分数
scorelist_student_target_Num=[] 
loc_target_Num =loc_target_two


for i in range(len(loc_target_Num)): 
    scorelist_student_target_Num.append( Qimo_score[:,loc_target_Num[i]] ) 
scorearr_target_Num = np.array(scorelist_student_target_Num).T 
# print('学生分数', scorearr_target_Num) 

# 每题题目分数 
FullscoreEEQ_list_target_Num=[] 
for i in range(len(loc_target_Num)):   
    FullscoreEEQ_list_target_Num.append(Fullscore_each_examination_question[loc_target_Num[i]] )  

# print('每题题目分数', FullscoreEEQ_list_target_Num)

### 数据计算
# 实际满分(百分制) - 比例满分 - 学生得分 - 得分比例 - 目标1得分
RealFullscore_target_Num_Total = sum(FullscoreEEQ_list_target_Num) / np.sum(Fullscore_each_examination_question)  *100  # 实际满分(百分制)
print('实际满分(百分制)', RealFullscore_target_Num_Total)
# 比例满分 (乘以比例后的分数) 
RatioFullscore_target_Num = RealFullscore_target_Num_Total * RATIO_SCORE_CLASS 
# 学生得分
Score_student_target_Num_Total = np.sum(scorearr_target_Num, axis=1) 
# 得分比例
Ratio_score_target_Num = np.around((Score_student_target_Num_Total/RealFullscore_target_Num_Total).astype(float) ,decimals=3)
print( Ratio_score_target_Num ) 
# 目标1得分 = 比例满分 * 得分比例 
Score_target_Num =np.around( ( RatioFullscore_target_Num * Ratio_score_target_Num).astype(float) ,decimals=3)
print(Score_target_Num)

实际满分(百分制) 22.0
[1.    1.    0.864 0.818 1.    1.    0.773 1.    0.864 0.864 0.864 0.773
 0.864 0.864 0.773 0.864 0.864 0.773 0.864 0.955 1.    1.    0.909 1.
 1.    1.    1.    1.    1.    0.864 0.818 0.864 0.909 1.    0.727 0.864
 0.864 1.    0.864 0.955 0.864 0.955 0.727 0.955 0.818 1.    0.864 1.
 0.818 1.    1.    0.864 0.818 0.818 0.818 0.818 1.    1.    0.818 0.864
 1.    1.    0.864 0.818 0.818 1.    1.    1.    0.818 1.    1.    1.
 1.    1.    1.    1.    0.864 1.    1.    1.   ]
[13.2   13.2   11.405 10.798 13.2   13.2   10.204 13.2   11.405 11.405
 11.405 10.204 11.405 11.405 10.204 11.405 11.405 10.204 11.405 12.606
 13.2   13.2   11.999 13.2   13.2   13.2   13.2   13.2   13.2   11.405
 10.798 11.405 11.999 13.2    9.596 11.405 11.405 13.2   11.405 12.606
 11.405 12.606  9.596 12.606 10.798 13.2   11.405 13.2   10.798 13.2
 13.2   11.405 10.798 10.798 10.798 10.798 13.2   13.2   10.798 11.405
 13.2   13.2   11.405 10.798 10.798 13.2   13.2   13.2   10.798 13.2
 13.2   13.2 