In [1]:
import os
import xlwings
import numpy as np
import pandas as pd 

In [2]:
# 常量设置
RATIO_USUAL_SCORE = 0.2  # 平时成绩比例
RATIO_EXPERIMENT = 0.2   # 实验成绩比例
RATIO_FINAL_SCORE = 0.6  # 期末成绩比例
RATIO_SCORE_CLASS= RATIO_FINAL_SCORE

In [3]:
Qimo_table = pd.read_excel('2022春_B机制191-192流体力学基础与液压气动技术-V2-20221108.xlsx', 
                                   index_col=None, header=None, sheet_name='期末考试')
print(Qimo_table)
course_target_class = np.array((Qimo_table.iloc[3,4:-1])) 
print(course_target_class) 


     0       1             2       3        4    5    6    7    8    9    10  \
0   NaN     NaN           NaN     NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1   NaN     NaN           NaN     NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2   NaN     NaN           NaN      题型  简答题（60）  NaN  NaN  NaN  NaN  NaN  NaN   
3   NaN     NaN           NaN  课程目标类别        1    1    1    1    2    2    3   
4   NaN     NaN           NaN    每题分值        6    6    6    6    6    6    6   
..  ...     ...           ...     ...      ...  ...  ...  ...  ...  ...  ...   
81   76  B机制192  190701011068     曹远荣        6    6    6    6    6    6    6   
82   77  B机制192  190701011073     朱亚东        6    6    6    6    6    6    6   
83   78  B机制192  190701011137     冯猛超        6    6    6    6    6    6    6   
84   79  B机制192  190701011138     姚宗君        4    6    6    6    6    6    6   
85   80  B机制192  190701011149     罗治华        6    6    6    6    6    6    6   

     11   12   13       14   15       1

In [4]:
Qimo_score = np.array(Qimo_table.iloc[6:,4:-1]) 
Qimo_score[:,0]


array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       5, 6, 6, 5, 6, 6, 6, 6, 6, 4, 6, 6, 5, 6, 6, 6, 6, 6, 6, 4, 6, 4,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6], dtype=object)

In [5]:
loc_target_one = np.argwhere(course_target_class==1).reshape((-1)) # 满足条件的索引值
loc_target_two = np.argwhere(course_target_class==2).reshape((-1)) # 满足条件的索引值
loc_target_three = np.argwhere(course_target_class==3).reshape((-1)) # 满足条件的索引值

print(loc_target_one,loc_target_two,loc_target_three)  

[ 0  1  2  3 10] [ 4  5 11] [ 6  7  8  9 12]


In [6]:
Fullscore_each_examination_question = np.array((Qimo_table.iloc[4,4:-1])).reshape((-1))
print(Fullscore_each_examination_question) 

[6 6 6 6 6 6 6 6 6 6 10 10 20]


In [7]:
np.sum(Fullscore_each_examination_question,axis=0)

100

In [56]:
# 达成度目标 = Num123 计算 
### 数据索引 
# 学生分数 
scorelist_student_target_one=[] 

for i in range(len(loc_target_one)): 
    scorelist_student_target_one.append( Qimo_score[:,loc_target_one[i]] ) 
scorearr_target_one = np.array(scorelist_student_target_one).T 
# print('学生分数', scorearr_target_one) 

# 每题题目分数 
FullscoreEEQ_list_target_one=[] 
for i in range(len(loc_target_one)):   
    FullscoreEEQ_list_target_one.append(Fullscore_each_examination_question[loc_target_one[i]] )  

# print('每题题目分数', FullscoreEEQ_list_target_one)

### 数据计算
# 实际满分(百分制) - 比例满分 - 学生得分 - 得分比例 - 目标1得分
RealFullscore_target_one_Total = sum(FullscoreEEQ_list_target_one) / np.sum(Fullscore_each_examination_question)  *100  # 实际满分(百分制)
print('实际满分(百分制)', RealFullscore_target_one_Total)
# 比例满分 (乘以比例后的分数) 
RatioFullscore_target_one = RealFullscore_target_one_Total * RATIO_SCORE_CLASS 
# 学生得分
Score_student_target_one_Total = np.sum(scorearr_target_one, axis=1) 
# 得分比例
Ratio_score_target_one = np.around((Score_student_target_one_Total/RealFullscore_target_one_Total).astype(float) ,decimals=3)
print( Ratio_score_target_one ) 
# 目标1得分 = 比例满分 * 得分比例 
Score_target_one =np.around( ( RatioFullscore_target_one * Ratio_score_target_one).astype(float) ,decimals=3)

print(Score_target_one)
print(type(Score_student_target_one_Total), Ratio_score_target_one.shape)
np.c_[ Score_student_target_one_Total, Ratio_score_target_one, Score_target_one]

实际满分(百分制) 34.0
[1.    1.    1.    0.912 1.    0.971 1.    1.    1.    1.    0.941 1.
 0.971 1.    0.971 0.971 0.971 0.971 0.971 1.    1.    1.    0.971 1.
 1.    0.912 1.    0.971 1.    1.    1.    0.941 1.    1.    0.941 0.971
 0.971 1.    0.941 0.971 1.    0.941 1.    0.941 1.    0.912 1.    1.
 1.    1.    0.971 1.    1.    1.    0.912 0.971 0.971 1.    0.971 0.912
 1.    1.    1.    1.    1.    1.    1.    1.    0.912 1.    1.    1.
 1.    1.    1.    1.    1.    1.    0.941 1.   ]
[20.4   20.4   20.4   18.605 20.4   19.808 20.4   20.4   20.4   20.4
 19.196 20.4   19.808 20.4   19.808 19.808 19.808 19.808 19.808 20.4
 20.4   20.4   19.808 20.4   20.4   18.605 20.4   19.808 20.4   20.4
 20.4   19.196 20.4   20.4   19.196 19.808 19.808 20.4   19.196 19.808
 20.4   19.196 20.4   19.196 20.4   18.605 20.4   20.4   20.4   20.4
 19.808 20.4   20.4   20.4   18.605 19.808 19.808 20.4   19.808 18.605
 20.4   20.4   20.4   20.4   20.4   20.4   20.4   20.4   18.605 20.4
 20.4   20.4   20.4   

array([[34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [31, 0.912, 18.605],
       [34, 1.0, 20.4],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [32, 0.941, 19.196],
       [34, 1.0, 20.4],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [33, 0.971, 19.808],
       [33, 0.971, 19.808],
       [33, 0.971, 19.808],
       [33, 0.971, 19.808],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [31, 0.912, 18.605],
       [34, 1.0, 20.4],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [32, 0.941, 19.196],
       [34, 1.0, 20.4],
       [34, 1.0, 20.4],
       [32, 0.941, 19.196],
       [33, 0.971, 19.808],
       [33, 0.971, 19.808],
       [34, 1.0, 20.4],
       [32, 0.941, 19.19

In [47]:
# 达成度目标=NUM 计算
### 数据索引
# 学生分数
def Achievement_Degree_Calcultion_function(loc_target_Num , RATIO_SCORE_CLASS ):  
    scorelist_student_target_Num=[] 

    for i in range(len(loc_target_Num)): 
        scorelist_student_target_Num.append( Qimo_score[:,loc_target_Num[i]] ) 
    scorearr_target_Num = np.array(scorelist_student_target_Num).T 
    # print('学生分数', scorearr_target_Num) 

    # 每题题目分数 
    FullscoreEEQ_list_target_Num=[] 
    for i in range(len(loc_target_Num)):   
        FullscoreEEQ_list_target_Num.append(Fullscore_each_examination_question[loc_target_Num[i]] )  

    # print('每题题目分数', FullscoreEEQ_list_target_Num)

    ### 数据计算
    # 实际满分(百分制) - 比例满分 - 学生得分 - 得分比例 - 目标1得分
    RealFullscore_target_Num_Total = sum(FullscoreEEQ_list_target_Num) / np.sum(Fullscore_each_examination_question)  *100  # 实际满分(百分制)
    print('实际满分(百分制)', RealFullscore_target_Num_Total)
    # 比例满分 (乘以比例后的分数) 
    RatioFullscore_target_Num = RealFullscore_target_Num_Total * RATIO_SCORE_CLASS 
    # 学生得分
    Score_student_target_Num_Total = np.sum(scorearr_target_Num, axis=1) 
    # 得分比例
    Ratio_score_target_Num = np.around((Score_student_target_Num_Total/RealFullscore_target_Num_Total).astype(float) ,decimals=3)
    # print( Ratio_score_target_Num ) 
    # 目标1得分 = 比例满分 * 得分比例 
    Score_target_Num =np.around( ( RatioFullscore_target_Num * Ratio_score_target_Num).astype(float) ,decimals=3)
    # print(Score_target_Num)
    
    return np.c_[Score_student_target_Num_Total, Ratio_score_target_Num, Score_target_Num]

In [50]:
target_one_arr = Achievement_Degree_Calcultion_function(loc_target_Num = loc_target_one, RATIO_SCORE_CLASS= 0.6 )
target_two_arr = Achievement_Degree_Calcultion_function(loc_target_Num = loc_target_two, RATIO_SCORE_CLASS= 0.6 )
target_three_arr = Achievement_Degree_Calcultion_function(loc_target_Num = loc_target_three, RATIO_SCORE_CLASS= 0.6 )

实际满分(百分制) 34.0
[1.    1.    1.    0.912 1.    0.971 1.    1.    1.    1.    0.941 1.
 0.971 1.    0.971 0.971 0.971 0.971 0.971 1.    1.    1.    0.971 1.
 1.    0.912 1.    0.971 1.    1.    1.    0.941 1.    1.    0.941 0.971
 0.971 1.    0.941 0.971 1.    0.941 1.    0.941 1.    0.912 1.    1.
 1.    1.    0.971 1.    1.    1.    0.912 0.971 0.971 1.    0.971 0.912
 1.    1.    1.    1.    1.    1.    1.    1.    0.912 1.    1.    1.
 1.    1.    1.    1.    1.    1.    0.941 1.   ]
[20.4   20.4   20.4   18.605 20.4   19.808 20.4   20.4   20.4   20.4
 19.196 20.4   19.808 20.4   19.808 19.808 19.808 19.808 19.808 20.4
 20.4   20.4   19.808 20.4   20.4   18.605 20.4   19.808 20.4   20.4
 20.4   19.196 20.4   20.4   19.196 19.808 19.808 20.4   19.196 19.808
 20.4   19.196 20.4   19.196 20.4   18.605 20.4   20.4   20.4   20.4
 19.808 20.4   20.4   20.4   18.605 19.808 19.808 20.4   19.808 18.605
 20.4   20.4   20.4   20.4   20.4   20.4   20.4   20.4   18.605 20.4
 20.4   20.4   20.4   

In [60]:
ScoreTotal_Cal_CourseClass_0 = target_one_arr[:,2] + target_two_arr[:,2] + target_three_arr[:,2]
print(ScoreTotal_Cal_CourseClass_0 )
ScoreTotal_Real_CourseClass_0 = np.sum(Qimo_score, axis=1) * RATIO_SCORE_CLASS
print(ScoreTotal_Real_CourseClass_0) 

[56.989999999999995 55.80199999999999 54.007000000000005 52.793
 56.989999999999995 55.818 53.414 58.205 54.614999999999995 55.195 53.991
 53.994 54.603 55.195 53.402 54.022999999999996 55.211 54.010000000000005
 54.603 55.816 57.598 56.41 53.402 56.41 56.989999999999995 55.195
 56.989999999999995 57.613 57.598 55.195 54.007999999999996
 54.599000000000004 55.789 57.598 52.182 55.818 56.425 57.598 53.991
 57.019000000000005 56.41 55.192 52.806 55.8 54.007999999999996
 54.614999999999995 55.195 55.80199999999999 54.007999999999996 56.41
 56.397999999999996 55.803 54.007999999999996 55.196 53.400999999999996
 53.996 57.006 56.41 54.604 54.614999999999995 57.598 55.80199999999999
 55.195 54.588 54.588 55.19499999999999 56.989999999999995
 56.989999999999995 53.400999999999996 56.41 56.41 55.80199999999999
 56.989999999999995 56.989999999999995 57.598 58.205 55.195 56.41 53.384
 56.41]
[57.0 55.8 54.0 52.8 57.0 55.8 53.4 58.199999999999996 54.6
 55.199999999999996 54.0 54.0 54.6 55.1999999